### ISSUE TITLE
Release 0.69.0 does not build on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by FlameSoulis** [highfidelity/hifi#13541]
This new version does NOT compile the assignment-client at all on Ubuntu 16.04:
```
[ 85%] Building CXX object libraries/physics/CMakeFiles/physics.dir/src/CharacterRayResult.cpp.o
/home/root/src/hifi/libraries/physics/src/CharacterRayResult.cpp: In constructor ‘CharacterRayResult::CharacterRayResult(const CharacterGhostObject*)’:
/home/root/src/hifi/libraries/physics/src/CharacterRayResult.cpp:23:42: error: invalid initialization of non-const reference of type ‘int32_t& {aka int&}’ from an rvalue of type ‘int32_t {aka int}’
     _character->getCollisionGroupAndMask(m_collisionFilterGroup, m_collisionFilterMask);
                                          ^
In file included from /home/root/src/hifi/libraries/physics/src/CharacterRayResult.cpp:16:0:
/home/root/src/hifi/libraries/physics/src/CharacterGhostObject.h:32:10: note:   initializing argument 1 of ‘void CharacterGhostObject::getCollisionGroupAndMask(int32_t&, int32_t&) const’
     void getCollisionGroupAndMask(int32_t& group, int32_t& mask) const;
          ^
libraries/physics/CMakeFiles/physics.dir/build.make:86: recipe for target 'libraries/physics/CMakeFiles/physics.dir/src/CharacterRayResult.cpp.o' failed
```
This was not a problem when compiling 0.68.1.

GCC Version: 5.4.0.20160609
Qt Version. 5.10.1
CMake Version: 3.5.1

**Comment by FlameSoulis** [comment]
This issue is no longer relevant and does not appear in the current builds.
