### PR TITLE
build fixes

### PR DESCRIPTION
**Pull request by ChristophHaag**
With gcc 5 nullptr can't be used as bool. With a cast it works.

The other one should be self explanatory. Was broken in https://github.com/highfidelity/hifi/commit/c17c9f181880b33553201ae1ad9c3c287c11321b/

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
An admin must verify this patch for the pull request build to fire. Type "ok to test" to begin testing this pull request or "add to whitelist" to test this and all future pull requests from this collaborator.

**Comment by sethalves** [comment]
ok to test

**Comment by sethalves** [comment]
add to whitelist

**Comment by sethalves** [comment]
test this please

**Comment by murillodigital** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Build console output for commit: 6a8f131a8351b99bea89143876ea862d086af253 available at: https://gist.github.com/8b6432ac94a430f8310d<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5731.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5731.dmg

**Comment by ChristophHaag** [comment]
Hm, the OS X error message is not wrong. The macros are used in functions that return a pointer instead of a bool. I should have looked closer at the error message

```
[ 45%] Building CXX object libraries/animation/CMakeFiles/animation.dir/src/AnimNodeLoader.cpp.o
/home/chris/oldhome/build/hifi/hifi/libraries/animation/src/AnimNodeLoader.cpp: In function 'bool processStateMachineNode(AnimNode::Pointer, const QJsonObject&, const QString&, const QUrl&)':
/home/chris/oldhome/build/hifi/hifi/libraries/animation/src/AnimNodeLoader.cpp:78:16: error: converting to 'bool' from 'std::nullptr_t' requires direct-initialization [-fpermissive]
         return nullptr;                                                 \
                ^
/home/chris/oldhome/build/hifi/hifi/libraries/animation/src/AnimNodeLoader.cpp:281:5: note: in expansion of macro 'READ_STRING'
     READ_STRING(currentState, jsonObj, nodeId, jsonUrl);
     ^
```
The problem is that the READ_STRING macro (and others) is used both in functions that return a bool and in functions that return a pointer.

gcc5 does not convert nullptr to a bool, but it looks like it converts a "nulled" bool to a pointer just fine. And the compiler on Mac OS X seems convert the opposite.

**Comment by ChristophHaag** [comment]
I guess extending the macros to take the desired return value in the error case would be a possibility that should satisfy all compilers but it seems kinda ugly.

Maybe @hyperlogic could chime in how to best solve this issue since he added the macro and the use of the macro in a function that returns bool:

https://github.com/highfidelity/hifi/commit/3286a32afc543c9b2d1682f5ddf3e415054a45f9#diff-f0172033ef8226f6ef285a04180b9fa9R273

**Comment by murillodigital** [comment]
ok to test

**Comment by hifi-gustavo** [comment]
Build console output for commit: ddcee763ca68db0c96c5721c42c85df881d22374 available at: https://gist.github.com/8b6432ac94a430f8310d<br/><br/>Installers available for download at: <br/>Windows: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5731.exe<br/>OS X: http://s3.amazonaws.com/hifi-public/pr-builds/dev-interface-5731.dmg

**Comment by hyperlogic** [comment]
:+1: looks good to me
