### PR TITLE
Android: Hide menu and fix shader compilation

### PR DESCRIPTION
**Pull request by SamGondelman**
Fixes issues caused by https://github.com/highfidelity/hifi/pull/12911 and https://github.com/highfidelity/hifi/pull/12873

Lots of small shader changes but they're purely renaming variables for consistency because we use different combinations of them and the varyings need to match.  Shouldn't need to test beyond a sanity check.

Test plan:
- Open Interface (Windows and Mac, NVIDIA and AMD).  Check your logs.  You shouldn't see any shader compilation warnings.
- Open Interface on Android.  You shouldn't see the menu bar (File, Edit, etc.) at the top.  The logs shouldn't have any shader compilation errors.

### CODE REVIEW

**Comment by hifi-gustavo** [comment]
Android build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dandroid/9016/app_12962_PR_ac7e8623bf42a7fb123a916f5b15201158775a16.apk

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9016/HighFidelity-Beta-PR12962-ac7e8623bf42a7fb123a916f5b15201158775a16.dmg

**Comment by hifi-gustavo** [comment]
Mac OS X client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/9016/HighFidelity-Beta-Interface-PR12962-ac7e8623bf42a7fb123a916f5b15201158775a16.dmg

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9016/HighFidelity-Beta-PR12962-ac7e8623bf42a7fb123a916f5b15201158775a16.exe

**Comment by hifi-gustavo** [comment]
Windows client-only build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/9016/HighFidelity-Beta-Interface-PR12962-ac7e8623bf42a7fb123a916f5b15201158775a16.exe

**Comment by qlimnavarro** [comment]
Currently Testing

**Comment by qlimnavarro** [comment]
Pass @conklin94122 22 
Shader warning still appears on AMD devices, if once 12921 is passed and merged we'd be happy to retest.

**Comment by conklin94122** [comment]
@L370 ran Android smoke, all tests passed. Phew. Thanks George.
