### PR TITLE
fix linux build on g++-6.2.0

### PR DESCRIPTION
**Pull request by AndrewMeadows**

### CODE REVIEW

**Comment by AndrewMeadows** [comment]
The build error only showed up in DEBUG mode because otherwise the `assert()` would hide the problem:
```
libraries/entities-renderer/src/RenderableModelEntityItem.cpp:411:26: error: ‘ModelPointer ModelEntityWrapper::_model’ is private within this context
```

**Comment by sethalves** [comment]
https://github.com/highfidelity/hifi/issues/11386

**Comment by hifi-gustavo** [comment]
Windows build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/3402/HighFidelity-Beta-PR11395-b97ad5892b35e31081e045181a34d6019559579b.exe

**Comment by sethalves** [comment]
build this please

**Comment by AndrewMeadows** [comment]
Jenkins, rebuild this please.

**Comment by hifi-gustavo** [comment]
Mac OS X build is available at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/3410/HighFidelity-Beta-PR11395-b97ad5892b35e31081e045181a34d6019559579b.dmg

**Comment by AndrewMeadows** [comment]
@Jherico, I'll close this PR.  You're welcome to fix the DEBUG builds.
